sudo: true
language: java
install: true
addons:
  sonarcloud:
    organization: $SONAR_ORGNIZATION
    token: $SONAR_TOKEN
jdk:
  - oraclejdk8
script:
# Remove the old dependency JARs, since they were stale for some reason.
#  - rm $HOME/.m2/repository/org/onebeartoe/onebeartoe-application/1.0/onebeartoe-application-1.0.jar
#  - rm $HOME/.m2/repository/org/onebeartoe/onebeartoe-application/1.0/onebeartoe-application-1.0.pom
  
# Set the .m2/settings repository, since onebeartoe.org repository was not acknowledge from the project POM.
  - cat $HOME/.m2/settings.xml
#TODO: revisit this and see if it was just the <releases> that was needed in the projet POM  
#      this is the stackoverflow question that suggestion overwritting the .m2/settings.xml file.
#  - cp  settings.xml $HOME/.m2/settings.xml
#  - cat $HOME/.m2/settings.xml

# build and scan the applications
  - mvn -e clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
