sudo: true
dist: trusty
language: java
install: true
addons:
  sonarcloud:
    organization: $SONAR_ORGNIZATION
    token: $SONAR_TOKEN
jdk:
  - oraclejdk8
script:
  - mvn --quiet clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
