sudo: true
language: java
install: true
addons:
  sonarcloud:
    organization: $SONAR_ORGNIZATION
    token: $SONAR_TOKEN
jdk:
  - oraclejdk8
script:
  - cat $HOME/.m2/settings.xml
  - cp  settings.xml $HOME/.m2/settings.xml
  - cat $HOME/.m2/settings.xml
  - mvn -e clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
